# Generated by Django 4.1.3 on 2023-09-22 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0007_hoteleventcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelEventA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventDescription', models.TextField(max_length=1000, verbose_name='Event Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Event A',
            },
        ),
        migrations.CreateModel(
            name='HotelEventB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventDescription', models.TextField(max_length=1000, verbose_name='Event Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Event B',
            },
        ),
        migrations.CreateModel(
            name='HotelEventCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200, verbose_name='Category Name')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Event Categories',
            },
        ),
        migrations.CreateModel(
            name='HotelEventAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlertID', models.CharField(max_length=500, verbose_name='Code')),
                ('ReceivedBy', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Received By')),
                ('PhoneNo', models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone No')),
                ('Message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Message')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hoteleventcategories', verbose_name='Category')),
                ('EventA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteleventa', verbose_name='Event A')),
                ('EventB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteleventb', verbose_name='Event B')),
            ],
            options={
                'verbose_name_plural': 'Hotel Event Code',
            },
        ),
    ]
