# Generated by Django 4.1.3 on 2023-09-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0008_hoteleventa_hoteleventb_hoteleventcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteleventalert',
            name='ReceivedBy',
            field=models.EmailField(blank=True, max_length=1000, null=True, verbose_name='Received By'),
        ),
    ]
