# Generated by Django 4.1.3 on 2023-09-23 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0009_alter_hoteleventalert_receivedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelfoodorder',
            name='orderItems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelfoodorderitems'),
        ),
    ]
