# Generated by Django 4.1.3 on 2023-09-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0010_hotelfoodorder_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelfoodorder',
            name='orderItems',
        ),
        migrations.AddField(
            model_name='hotelfoodorder',
            name='orderItems',
            field=models.ManyToManyField(blank=True, null=True, to='HotelApis.hotelfoodorderitems'),
        ),
    ]
