# Generated by Django 4.1.3 on 2023-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0011_remove_hotelfoodorder_orderitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldrinksorder',
            name='orderItems',
            field=models.ManyToManyField(blank=True, null=True, to='HotelApis.hoteldrinksorderitems'),
        ),
        migrations.AddField(
            model_name='hotelroomsorder',
            name='orderItems',
            field=models.ManyToManyField(blank=True, null=True, to='HotelApis.hotelroomsorderitems'),
        ),
    ]
