# Generated by Django 4.1.3 on 2023-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetailsApis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsdrinksorder',
            name='orderItems',
            field=models.ManyToManyField(blank=True, null=True, to='RetailsApis.retailsdrinksorderitems'),
        ),
        migrations.AddField(
            model_name='retailsfoodorder',
            name='orderItems',
            field=models.ManyToManyField(blank=True, null=True, to='RetailsApis.retailsfoodorderitems'),
        ),
    ]
