# Generated by Django 4.1.3 on 2023-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdrinksorder',
            name='orderItems',
            field=models.ManyToManyField(blank=True, null=True, to='RestaurantApis.restaurantdrinksorderitems'),
        ),
        migrations.AddField(
            model_name='restaurantfoodorder',
            name='orderItems',
            field=models.ManyToManyField(blank=True, null=True, to='RestaurantApis.restaurantfoodorderitems'),
        ),
    ]
